### ISSUE TITLE
chain A in 1R6F occurs more than once after cleaning

### ISSUE THREAD

**Issue by jonblack** [cmbi/hommod-api#54]
The following job in HOPE fails because of the error below in hommod:

The sequence:
>MERAESSSTEPAKAIKPIDRKSVHQICSGQVVLSLSTAVKELVENSLDAGATNIDLKLKDYGVDLIEVSDNGCGVEEENFEGLTLKHHTSKIQEFADLTQVETFGFRGEALSSLCALSDVTISTCHASAKVGTRLMFDHNGKIIQKTPYPRPRGTTVSVQQLFSTLPVRHKEFQRNIKKEYAKMVQVLHAYCIISAGIRVSCTNQLGQGKRQPVVCTGGSPSIKENIGSVFGQKQLQSLIPFVQLPPSDSVCEEYGLSCSDALHNLFYISGFISQCTHGVGRSSTDRQFFFINRRPCDPAKVCRLVNEVYHMYNRHQYPFVVLNISVDSECVDINVTPDKRQILLQEEKLLLAVLKTSLIGMFDSDVNKLNVSQQPLLDVEGNLIKMHAADLEKPMVEKQDQSPSLRTGEEKKDVSISRLREAFSLRHTTENKPHSPKTPEPRRSPLGQKRGMLSSSTSGAISDKGVLRPQKEAVSSSHGPSDPTDRAEVEKDSGHGSTSVDSEGFSIPDTGSHCSSEYAASSPGDRGSQEHVDSQEKAPETDDSFSDVDCHSNQEDTGCKFRVLPQPTNLATPNTKRFKKEEILSSSDICQKLVNTQDMSASQVDVAVKINKKVVPLDFSMSSLAKRIKQLHHEAQQSEGEQNYRKFRAKICPGENQAAEDELRKEISKTMFAEMEIIGQFNLGFIITKLNEDIFIVDQHATDEKYNFEMLQQHTVLQGQRLIAPQTLNLTAVNEAVLIENLEIFRKNGFDFVIDENAPVTERAKLISLPTSKNWTFGPQDVDELIFMLSDSPGVMCRPSRVKQMFASRACRKSVMIGTALNTSEMKKLITHMGEMDHPWNCPHGRPTMRHIANLGVISQN 

Mutation: `P470S`

The template:

```
{'file_path': None, 'template': {'required_identity': 23.28984896457817, 'ac_code': '1R6F', 'chain': 'A', 'identity': 44}} 
```

The exception is:

```
        Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/src/app/hope/factory.py", line 171, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/hope/tasks.py", line 233, in get_structure_features
    model = modeler.from_sequence(sequence, position, template_id)
  File "/usr/src/app/hope/domain/modeler.py", line 12, in from_sequence
    template_id)
  File "/usr/src/app/hope/services/hommod.py", line 68, in run
    raise ServiceError(json.loads(r.text)['message'])
hope.services.types.ServiceError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/src/app/hommod_rest/factory.py", line 96, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/hommod_rest/tasks.py", line 38, in create_model
    template_id)
  File "/usr/src/app/hommod_rest/services/model.py", line 849, in modelProc
    self._set_template(chosenTemplateID.pdbac)
  File "/usr/src/app/hommod_rest/services/model.py", line 412, in _set_template
    raise Exception("chain %s in %s occurs more than once after cleaning" % (chain, tempac))
Exception: chain A in 1R6F occurs more than once after cleaning
```

**Comment by cbaakman** [comment]
This issue has been fixed in #56

**Comment by jonblack** [comment]
This exception has appeared again:

```
Message type: ERROR
Location: /usr/src/app/hope/services/hommod.py:68
Module: hommod
Function: run
Time: 2017-06-11 23:28:12,349
Message:
Model job failed:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/src/app/hommod_rest/factory.py", line 96, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/hommod_rest/tasks.py", line 67, in create_model
    template_id)
  File "/usr/src/app/hommod_rest/services/model.py", line 816, in modelProc
    self._set_template(chosenTemplateID.pdbac)
  File "/usr/src/app/hommod_rest/services/model.py", line 370, in _set_template
    raise Exception("chain %s in %s occurs more than once after cleaning" % (chain, tempac))
Exception: chain l in 5MQF occurs more than once after cleaning
```

**Comment by cbaakman** [comment]
5MQF is mentioned in https://github.com/cmbi/hope/issues/444. It's one of the templates that should be avoided. Once the following pull request gets merged: https://github.com/cmbi/hope/pull/457, hope shouldn't come up with 5MQF ever again.

**Comment by jonblack** [comment]
But doesn't the error still imply that the bug in this issue isn't fixed?

**Comment by cbaakman** [comment]
First of all, it's not the same error. This message is a general error message that could pop up for any type of problem.
Second, to make hommod work with templates like 5MQF, it would need to check for chain breaks everywhere in the structure, which would take a lot of time, making hommod slower.

**Comment by jonblack** [comment]
So this error could appear more often in the future but doesn't necessarily indicate a problem?

**Comment by cbaakman** [comment]
It does indicate a problem, but it's not necessarily the same kind of problem.
There was indeed a bug, I've fixed it in https://github.com/cmbi/hommod-api/pull/73/commits/f8cd58069b82489fbfa8cf984fee2d6c878d916c
